-- Inserção de 50 produtos
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Cerveja Heineken Long Neck', 9.50, 1);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Caipirinha de Limão', 12.00, 8);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Porção de Batata Frita', 18.00, 3);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Refrigerante Lata', 6.00, 2);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Hambúrguer Artesanal', 22.00, 5);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Cerveja Skol 600ml', 7.50, 1);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Água com Gás', 4.00, 2);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Espetinho de Frango', 8.00, 4);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Calabresa Acebolada', 19.00, 3);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Caipiroska de Morango', 15.00, 8);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Pastel de Queijo', 7.00, 4);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Cerveja Brahma Duplo Malte', 8.00, 1);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Porção de Mandioca Frita', 17.00, 3);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Suco Natural de Laranja', 8.00, 2);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Cachaça Artesanal', 10.00, 1);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Bolinho de Feijoada', 9.50, 4);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Milkshake de Chocolate', 12.00, 6);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Combo de Mini Burgers', 25.00, 5);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Porção de Torresmo', 16.00, 3);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Negroni', 18.00, 8);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Batida de Coco', 11.00, 8);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Queijo Coalho na Brasa', 10.00, 4);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Brigadeiro Gourmet', 5.00, 6);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Churros com Doce de Leite', 8.00, 6);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Pastel de Carne Seca', 8.00, 4);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Cerveja IPA 500ml', 14.00, 7);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Porção de Frango à Passarinho', 20.00, 3);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Guaraná Natural', 6.50, 2);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Espetinho de Coração', 9.00, 4);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Tábua de Frios', 28.00, 9);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Brownie com Sorvete', 10.00, 6);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Shot de Tequila', 9.00, 1);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Suco Detox', 9.00, 2);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Hambúrguer com Bacon', 23.00, 5);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Porção de Polenta Frita', 17.00, 3);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Gin Tônica', 17.00, 8);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Doce de Abóbora com Coco', 7.00, 6);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Pipoca Artesanal', 5.00, 4);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Linguiça Artesanal Acebolada', 20.00, 9);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Cerveja Stout 500ml', 15.00, 7);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Drink de Maracujá com Rum', 16.00, 8);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Água Tônica', 5.50, 2);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Bolinho de Bacalhau', 12.00, 4);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Empanada Chilena', 10.00, 9);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Ice de Limão', 10.00, 1);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Rapadura com Queijo', 6.00, 6);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Vodka Nacional Dose', 7.00, 1);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Havana com Coca-Cola', 15.00, 8);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Narguilé com Essência Maçã', 30.00, 10);
INSERT INTO barzinho.produtos (nome_produto, preco_unitario, id_categoria) VALUES ('Charuto Cubano', 40.00, 10);
