/*
	FAZER UMA CONSULTA QUE RETORNE OS ITENS DO CARDAPIO QUE FORAM PEDIDOS (NOME DO PRODUTO, 
	NOME DA CATEGORIA E VALOR DO PRODUTO), O NÚMERO DA MESA E O NOME DO GARÇOM QUE ATENDEU A MESA. 
	
	LISTE APENAS AS MESAS ATENDIDAS NO DIA 08/06/2025
*/
